### PR TITLE
improve support for financial advisor

### PR DESCRIPTION
**Pull request by mengwong**
we improve the parser and transpiler to CoreL4 for both data modeling and decision modeling

### CODE REVIEW

**Comment by mengwong** [comment]
some of the previous work on SVGLadder seems to have ended up in this PR – is this going to be OK?

**Comment by mengwong** [comment]
anyway, if we run

```
┌─[mengwong@rosegold] - [~/src/smucclaw/dsl/lib/haskell/natural4] - [2022-08-22 01:50:20]
└─[0] <git:(interpreter 8382bc6✈) > stack run -- --workdir=workdir test/class-fa-2.csv
```

we will see
```

#
# outputted directly from XPile/CoreL4.hs
#



-- classes




-- boilerplate




-- decls

-- [investment]
decl Person
-- [investment]
decl investment


-- facts

fact <investment> fromList [(["Person"],((Nothing,[]),[])),(["investment"],((Nothing,[]),[HC2 {hHead = RPConstraint ["investment"] RPis ["savings"], hBody = Just (Leaf (RPConstraint ["savings account"] RPis ["inadequate"]))},HC2 {hHead = RPConstraint ["investment"] RPis ["stocks"], hBody = Just (All Nothing [Leaf (RPConstraint ["savings account"] RPis ["adequate"]),Leaf (RPConstraint ["income"] RPis ["adequate"])])},HC2 {hHead = RPConstraint ["investment"] RPis ["combination"], hBody = Nothing},HC2 {hHead = RPConstraint ["minSavings"] RPis ["dependents * 5000"], hBody = Nothing},HC2 {hHead = RPConstraint ["savings account"] RPis ["adequate"], hBody = Just (Leaf (RPConstraint ["amount saved"] RPgt ["minSavings"]))},HC2 {hHead = RPConstraint ["savings account"] RPis ["inadequate"], hBody = Nothing},HC2 {hHead = RPConstraint ["minIncome"] RPis ["15000 + 4000 * dependents"], hBody = Nothing},HC2 {hHead = RPMT ["income","is","adequate"], hBody = Just (Leaf (RPConstraint ["earnings"] RPgt ["minIncome"]))}]))]
fact <investment> fromList [(["Person"],((Nothing,[]),[])),(["investment"],((Nothing,[]),[HC2 {hHead = RPConstraint ["investment"] RPis ["savings"], hBody = Just (Leaf (RPConstraint ["savings account"] RPis ["inadequate"]))},HC2 {hHead = RPConstraint ["investment"] RPis ["stocks"], hBody = Just (All Nothing [Leaf (RPConstraint ["savings account"] RPis ["adequate"]),Leaf (RPConstraint ["income"] RPis ["adequate"])])},HC2 {hHead = RPConstraint ["investment"] RPis ["combination"], hBody = Nothing},HC2 {hHead = RPConstraint ["minSavings"] RPis ["dependents * 5000"], hBody = Nothing},HC2 {hHead = RPConstraint ["savings account"] RPis ["adequate"], hBody = Just (Leaf (RPConstraint ["amount saved"] RPgt ["minSavings"]))},HC2 {hHead = RPConstraint ["savings account"] RPis ["inadequate"], hBody = Nothing},HC2 {hHead = RPConstraint ["minIncome"] RPis ["15000 + 4000 * dependents"], hBody = Nothing},HC2 {hHead = RPMT ["income","is","adequate"], hBody = Just (Leaf (RPConstraint ["earnings"] RPgt ["minIncome"]))}]))]


-- defn from decision rules

defn minSavings : Integer -> Integer = \x : Integer -> dependents * 5000
defn minIncome : Integer -> Integer = \x : Integer -> 15000 + 4000 * dependents

# directToCore


rule <investment_1>
for Person
if savings_account == inadequate
then investment == savings


rule <investment_2>
for Person
if (savings_account == adequate && income == adequate)
then investment == stocks


rule <investment_3>
for Person
if TRUE
then investment == combination


rule <investment_4>
for Person
if TRUE
then minSavings == dependents_*_5000


rule <investment_5>
for Person
if amount_saved > minSavings
then savings_account == adequate


rule <investment_6>
for Person
if TRUE
then savings_account == inadequate


rule <investment_7>
for Person
if TRUE
then minIncome == 15000_+_4000_*_dependents


rule <investment_8>
for Person
if earnings > minIncome
then income is adequate

```

which is a good start

**Comment by mengwong** [comment]
as for the data modelling, if we run
```
┌─[mengwong@rosegold] - [~/src/smucclaw/dsl/lib/haskell/natural4] - [2022-08-22 01:54:15]
└─[0] <git:(interpreter 3e06a7b✈) > stack run -- --workdir=workdir test/class-fa-1.csv
natural4: output to workdir done
```

we will get
```

#
# outputted directly from XPile/CoreL4.hs
#



-- classes

class EarningsStatus
# ctype:
# (Just (InlineEnum TOne (("steady" :| ["unsteady"],Nothing) :| [])),[])

decl steady: EarningsStatus
decl unsteady: EarningsStatus



class FinancialStatus
# ctype:
# (Just (InlineEnum TOne (("adequate" :| ["inadequate"],Nothing) :| [])),[])

decl adequate: FinancialStatus
decl inadequate: FinancialStatus



class InvestmentStrategy
# ctype:
# (Just (InlineEnum TOne (("savings" :| ["stocks","combination"],Nothing) :| [])),[])

decl savings: InvestmentStrategy
decl stocks: InvestmentStrategy
decl combination: InvestmentStrategy



class Person


# children:
# CT (fromList [("amount saved",((Just (SimpleType TOne "Number"),[]),CT (fromList []))),("dependents",((Just (SimpleType TOne "Number"),[]),CT (fromList []))),("earnings",((Just (SimpleType TOne "Number"),[]),CT (fromList []))),("income",((Just (SimpleType TOne "FinancialStatus"),[]),CT (fromList []))),("investment",((Just (SimpleType TOne "InvestmentStrategy"),[]),CT (fromList []))),("isDead",((Just (SimpleType TOne "Boolean"),[]),CT (fromList []))),("savings account",((Just (SimpleType TOne "FinancialStatus"),[]),CT (fromList []))),("spendthrift",((Just (SimpleType TOne "Boolean"),[]),CT (fromList [])))])

decl amount saved: Person -> Number -> Boolean
decl dependents: Person -> Number -> Boolean
decl earnings: Person -> Number -> Boolean
decl income: Person -> FinancialStatus -> Boolean
decl investment: Person -> InvestmentStrategy -> Boolean
decl isDead: Person -> Boolean
decl savings account: Person -> FinancialStatus -> Boolean
decl spendthrift: Person -> Boolean



-- boilerplate

fact <EarningsStatusExhaustive>
for x: EarningsStatus
(x == steady) || (x == unsteady)

fact <EarningsStatusDisj>
(steady /= unsteady)

fact <FinancialStatusExhaustive>
for x: FinancialStatus
(x == adequate) || (x == inadequate)

fact <FinancialStatusDisj>
(adequate /= inadequate)

fact <InvestmentStrategyExhaustive>
for x: InvestmentStrategy
(x == savings) || (x == stocks) || (x == combination)

fact <InvestmentStrategyDisj>
(savings /= stocks) && (savings /= combination) && (stocks /= combination)



-- decls




-- facts




-- defn from decision rules



# directToCore







```

**Comment by kharus** [comment]
All changes from anyall it has are already in the main.
I don't understand why git is confused and showing diffs.
There shouldn't be any diffs.

**Pull request merged**
