### PR TITLE
Remove unused InterpreterOptions

### PR DESCRIPTION
**Pull request by fendor**
InterpreterOptions were unused in the codebase.

### CODE REVIEW

**Comment by fendor** [comment]
This is a split-off of #609, hopefully reducing the diff a *little* bit.

**Comment by ym-han** [comment]
This is a bigger-picture question about the 'Interpreter': what's the difference exactly between LS.Interpreter and your Renamer? I have the impression that there might be quite a bit of overlap in goals --- would the Renamer basically obsolete the 'Interpreter'? Should we just replace LS.Interpreter with the Renamer?

**Comment by fendor** [comment]
In my point of view, the `Interpreter` will become the interface that transpilers may use during transpilation. For example, the interpreter has a rule dependency graph. Such a graph is not intrinsic to renaming, so should not be part of the renaming step itself. However, the rule dependency graph construction may depend on renamed rules during construction in the future.

As such, I like the `LS.Interpreter` module, and I think we will need both, Renamer and Interpreter. But we likely will restructure and extract things that are currently part of `Interpreter` into separate components. Does that make sense?

**Review by ym-han — APPROVED** [review]
LGTM!

**Pull request merged**
