### PR TITLE
First draft of L4->LE transpiler, with graceful exit upon error when simplifying L4 hcs

### PR DESCRIPTION
**Pull request by ym-han**
The current draft of the transpiler, however, has **not** implemented all the desired functionality.

In particular, we still need to
* implement support for the ditto syntax
* implement more validation / checking for unsupported L4 operators and syntax
* figure out what to do about the RPor and RPand, pending Meng's decision on that
* add some unit tests
* if time permits: add some property-based tests

Co-authored-by: johsi-k <johsi.k@gmail.com>

### CODE REVIEW

**Comment by joewatt95** [comment]
Hi, this looks good so far! I've just added some commits (namely [this](https://github.com/smucclaw/dsl/pull/429/commits/271d9b50dcc791990c071348624485f29ee8fd24) and [this](https://github.com/smucclaw/dsl/pull/429/commits/65bf650aa655ca160653aec11cb62c1322d86a98)), which don't change the overall design or functionality. The former makes some small adjustments to appease the linter and the latter adds predefined templates for some of my predefined predicates in the prelude section.

**Comment by joewatt95** [comment]
I've just tried running this on (the csv of) my natural4 encoding of the insurance policy and am getting the following error:
```
natural4-exe: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:74:14 in base:GHC.Err
  undefined, called at src/LS/XPile/LogicalEnglish/SimplifyL4.hs:310:30 in natural4-0.1.0.0-23LualwXV7YEpVlIpdZSyA:LS.XPile.LogicalEnglish.SimplifyL4
```
which points to [this](https://github.com/smucclaw/dsl/blob/65bf650aa655ca160653aec11cb62c1322d86a98/lib/haskell/natural4/src/LS/XPile/LogicalEnglish/SimplifyL4.hs#L310) line.

**Comment by joewatt95** [comment]
Oh yay, thanks for fixing the bug in the latest commit. Output looks good at a first glance, and I'll continue inspecting it more thoroughly later.

**Comment by johsi-k** [comment]
@joewatt95 I've added a placeholder for RPor and RPand so it doesn't crash on your encoding, but we're still waiting to decide on which RPnary syntax we want to support on this asana task: https://app.asana.com/0/0/1205284504234406/f. 

There were some other errors involving ditto in your Natural4 encoding which were causing it to not parse as intended
image

**Comment by ym-han** [comment]
> this

just as an fyi @joewatt95 , there's a few outstanding issues im aware of: e.g., need to do find and replace for the dot and comma; need to implement support for the ditto syntax, etc.

**Pull request merged**
